spring:
  output:
    ansi:
      enabled: always
  jackson:
    serialization:
      indent_output: true
      write_dates_as_timestamps: false
      write_durations_as_timestamps: false

endpoints:
  health:
    sensitive: false

management:
  security:
    enabled: false